// Constants for admin pages
export const ADMIN_CONSTANTS = {
  SESSION_DURATION: 24 * 60 * 60 * 1000, // 24 hours in milliseconds
  STORAGE_KEY: 'adminPassword',
} as const;

export const MESSAGES = {
  SUCCESS: {
    ARCHIVE_ADDED: 'Архів додано.',
    ARCHIVE_UPDATED: 'Архів оновлено.',
    ARCHIVE_DELETED: 'Архів видалено.',
    CATEGORY_ADDED: 'Категорію додано.',
    CATEGORY_UPDATED: 'Категорію оновлено.',
    CATEGORY_DELETED: 'Категорію видалено.',
    GALLERY_ITEM_ADDED: 'Елемент галереї додано.',
    GALLERY_ITEM_UPDATED: 'Елемент галереї оновлено.',
    GALLERY_ITEM_DELETED: 'Елемент галереї видалено.',
    CREATE_SUCCESS: 'Успішно створено!',
    UPDATE_SUCCESS: 'Успішно оновлено!',
    DELETE_SUCCESS: 'Успішно видалено!',
    LOGIN_SUCCESS: 'Успішний вхід!',
  },
  ERROR: {
    LOAD_ARCHIVES: 'Не вдалося завантажити архіви.',
    LOAD_CATEGORIES: 'Не вдалося завантажити категорії.',
    LOAD_GALLERY: 'Не вдалося завантажити галерею.',
    DELETE_ARCHIVE: 'Не вдалося видалити архів.',
    DELETE_CATEGORY: 'Не вдалося видалити категорію.',
    DELETE_GALLERY_ITEM: 'Не вдалося видалити елемент галереї.',
    SAVE_ARCHIVE: 'Не вдалося зберегти архів.',
    SAVE_CATEGORY: 'Не вдалося зберегти категорію.',
    SAVE_GALLERY_ITEM: 'Не вдалося зберегти елемент галереї.',
    LOAD_FOR_EDIT_ARCHIVE: 'Не вдалося завантажити архів для редагування.',
    LOAD_FOR_EDIT_GALLERY: 'Не вдалося завантажити елемент галереї для редагування.',
    INVALID_PASSWORD: 'Неправильний пароль!',
    LOAD_EVENTS: 'Не вдалося завантажити події.',
  },
  VALIDATION: {
    REQUIRED_TITLE: "Заголовок обов'язковий.",
    REQUIRED_TEXT: "Текст обов'язковий.",
    REQUIRED_DESCRIPTION: "Опис обов'язковий.",
    REQUIRED_CATEGORY: "Категорія обов'язкова.",
    REQUIRED_CATEGORY_NAME: "Назва категорії обов'язкова.",
    REQUIRED_LOCATION: "Локація обов'язкова.",
    REQUIRED_CONTENT_TYPE: "Тип контенту обов'язковий.",
    INVALID_CONTENT_TYPE: "Неправильний тип контенту.",
  },
} as const;

export const CSS_CLASSES = {
  INPUT: 'p-2 border rounded w-full',
  BUTTON_PRIMARY: 'bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-600',
  BUTTON_SECONDARY: 'bg-gray-500 text-white py-2 px-4 rounded hover:bg-gray-600',
  BUTTON_DANGER: 'bg-red-500 text-white py-1 px-2 rounded hover:bg-red-600',
  BUTTON_WARNING: 'bg-yellow-500 text-white py-1 px-2 rounded mr-2 hover:bg-yellow-600',
  BUTTON_ADD_TAG: 'bg-blue-500 text-white py-1 px-2 rounded hover:bg-blue-600',
  BUTTON_EDIT: 'bg-yellow-500 text-white py-1 px-2 rounded mr-2 hover:bg-yellow-600',
  BUTTON_DELETE: 'bg-red-500 text-white py-1 px-2 rounded hover:bg-red-600',
  ERROR_MESSAGE: 'text-red-500 text-sm',
  LABEL: 'block font-medium',
  CARD: 'p-4 border rounded mb-4 flex justify-between items-center',
  TAG: 'flex items-center bg-gray-200 px-2 py-1 rounded',
  TAG_REMOVE: 'ml-2 text-red-500',
  FORM_GRID: 'grid grid-cols-2 gap-4',
  FORM_SUBMIT: 'mt-4 bg-blue-500 text-white py-2 px-4 rounded hover:bg-blue-600',
  CONTAINER: 'container mx-auto p-6',
  TITLE: 'text-3xl font-bold mb-6',
  SUBTITLE: 'text-2xl font-bold mb-4',
  FORM: 'bg-white p-6 rounded-lg shadow-md mb-6',
  CHECKBOX_CONTAINER: 'mb-4',
  CHECKBOX_LABEL: 'flex items-center',
  CHECKBOX: 'mr-2',
  LIST_CONTAINER: 'bg-white p-6 rounded-lg shadow-md',
  NO_DATA: 'text-gray-500 text-center',
  GRID: 'grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4',
  CARD_IMAGE_CONTAINER: 'w-full h-48 overflow-hidden rounded mb-4',
  CARD_IMAGE: 'w-full h-full object-cover',
  CARD_CONTENT: 'p-4',
  CARD_TITLE: 'text-lg font-bold mb-2',
  CARD_STATUS: 'text-gray-600 mb-2',
  CARD_ACTIONS: 'flex gap-2',
} as const;